### ISSUE TITLE
qt5-static undefined references

### ISSUE THREAD

**Issue by rokups** [msys2/MSYS2-packages#1765]
Unable to build anything linking to qt5-static. It used to work in the past (around Qt 5.10 version).

Reproduction steps:

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.13)
project(static_qt)
set(CMAKE_PREFIX_PATH "C:/msys64/mingw32/qt5-static")
find_package(Qt5 5 REQUIRED Core)
add_executable(static_qt main.cpp)
target_link_libraries(static_qt PUBLIC Qt5::Core)
```
main.cpp
```cpp
#include <QObject>

int main()
{
    QObject object;
    return 0;
}
```

Result:
```
====================[ Build | static_qt | Debug-mingw32 ]=======================
"C:\Program Files\JetBrains\CLion-2018.3.4\bin\cmake\win\bin\cmake.exe" --build C:\static-qt\cmake-build-debug-mingw32 --target static_qt -- -j 4
Scanning dependencies of target static_qt
[ 50%] Building CXX object CMakeFiles/static_qt.dir/main.cpp.obj
[100%] Linking CXX executable static_qt.exe
CMakeFiles\static_qt.dir/objects.a(main.cpp.obj): In function `main':
C:/static-qt/main.cpp:5: undefined reference to `QObject::QObject(QObject*)'
C:/static-qt/main.cpp:5: undefined reference to `QObject::~QObject()'
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [CMakeFiles\static_qt.dir\build.make:89: static_qt.exe] Error 1
mingw32-make[2]: *** [CMakeFiles\Makefile2:72: CMakeFiles/static_qt.dir/all] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:84: CMakeFiles/static_qt.dir/rule] Error 2
mingw32-make: *** [Makefile:117: static_qt] Error 2
```

**Comment by rokups** [comment]
I just realized i posted it on the wrong project. Please excuse me for the noise.
