### ISSUE TITLE
MSYS2 Perl CPAN install XML::Parser fails

### ISSUE THREAD

**Issue by orcmid** [msys2/MSYS2-packages#110]
I'm not certain where this defect belongs, but I'll start here because it happens under MSYS2.
Using MSYS2 Perl CPAN fails in the compilation of Expat with an unresolvable include.  Here's the failing build step:

```
gcc -c   -DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -fwrapv -fno-strict-aliasing -pipe -fstack-    protector -DUSEIMPORTLIB -march=x86-64 -mtune=generic -O2 -pipe   -DVERSION=\"2.41\"     
-DXS_VERSION=\"2.41\"  "-I/usr/lib/perl5/core_perl/CORE"   Expat.c
In file included from Expat.xs:15:0:
D:/msys64/usr/lib/perl5/core_perl/CORE/perl.h:776:25: fatal error: sys/wait.h: No such file or directory
#   include <sys/wait.h>
                         ^
compilation terminated.
Makefile:312: recipe for target 'Expat.o' failed
make[1]: *** [Expat.o] Error 1
make[1]: Leaving directory '/home/orcmid/.cpan/build/XML-Parser-2.41-ua8egY/Expat'
Makefile:590: recipe for target 'subdirs' failed
make: *** [subdirs] Error 2
    TODDR/XML-Parser-2.41.tar.gz
    /usr/bin/make -- NOT OK
```

The offending pre-processor complaint is in the following lines of perl.h:

```
/* for WCOREDUMP */
#ifdef I_SYS_WAIT
#   include <sys/wait.h>
#endif
```

I have not been able to find where in the compilation of Expat.c `I_SYS_WAIT` is set.  There is no sys/ sub-directory in the include path and no wait.h available otherwise. Since Expat.c is a generated file, I am also not clear where to fix this enough for the install to work.
